baseURL = "https://www.arctictern.studio/"
languageCode = "en-us"
title = "Arctic Tern"
theme = "mediumish"
copyright = "Arctic Tern 2019"

[params]
  logo = "/images/logo-base.jpg"
  logo_full = "/images/logo-wo-image.png"

[[menu.main]]
  name = "Podcast"
  weight = 100
  identifier = "podcast"
  url = "/podcast"

[[menu.main]]
  name = "Blog"
  weight = 200
  identifier = "blog"
  url = "/blog"

[[menu.main]]
  name = "About"
  weight = 300
  identifier = "what-is-arctic-tern"
  url = "/what-is-arctic-tern"
